/* Generated By:JavaCC: Do not edit this line. PrismParserConstants.java */
package parser;

public interface PrismParserConstants {

  int EOF = 0;
  int COMMENT = 5;
  int PROBABILISTIC = 6;
  int NONDETERMINISTIC = 7;
  int STOCHASTIC = 8;
  int BOOL = 9;
  int CEIL = 10;
  int CONST = 11;
  int DOUBLE = 12;
  int ENDMODULE = 13;
  int ENDSYSTEM = 14;
  int FALSE = 15;
  int FLOOR = 16;
  int FORMULA = 17;
  int GLOBAL = 18;
  int INIT = 19;
  int INT = 20;
  int LABEL = 21;
  int MAX = 22;
  int MIN = 23;
  int MODULE = 24;
  int P = 25;
  int PMIN = 26;
  int PMAX = 27;
  int PROB = 28;
  int RATE = 29;
  int S = 30;
  int SYSTEM = 31;
  int TRUE = 32;
  int UNTIL = 33;
  int NEXT = 34;
  int NOT = 35;
  int AND = 36;
  int OR = 37;
  int IMPLIES = 38;
  int RARROW = 39;
  int COLON = 40;
  int SEMICOLON = 41;
  int COMMA = 42;
  int DOTS = 43;
  int LPARENTH = 44;
  int RPARENTH = 45;
  int LBRACKET = 46;
  int RBRACKET = 47;
  int LBRACE = 48;
  int RBRACE = 49;
  int EQ = 50;
  int NE = 51;
  int LT = 52;
  int GT = 53;
  int LE = 54;
  int GE = 55;
  int PLUS = 56;
  int MINUS = 57;
  int TIMES = 58;
  int DIVIDE = 59;
  int PRIME = 60;
  int RENAME = 61;
  int QMARK = 62;
  int DQUOTE = 63;
  int REG_INT = 64;
  int REG_DOUBLE = 65;
  int REG_IDENTPRIME = 66;
  int REG_IDENT = 67;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<COMMENT>",
    "<PROBABILISTIC>",
    "<NONDETERMINISTIC>",
    "<STOCHASTIC>",
    "\"bool\"",
    "\"ceil\"",
    "\"const\"",
    "\"double\"",
    "\"endmodule\"",
    "\"endsystem\"",
    "\"false\"",
    "\"floor\"",
    "\"formula\"",
    "\"global\"",
    "\"init\"",
    "\"int\"",
    "\"label\"",
    "\"max\"",
    "\"min\"",
    "\"module\"",
    "\"P\"",
    "\"Pmin\"",
    "\"Pmax\"",
    "\"prob\"",
    "\"rate\"",
    "\"S\"",
    "\"system\"",
    "\"true\"",
    "\"U\"",
    "\"X\"",
    "\"!\"",
    "\"&\"",
    "\"|\"",
    "\"=>\"",
    "\"->\"",
    "\":\"",
    "\";\"",
    "\",\"",
    "\"..\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\"=\"",
    "\"!=\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"\\\'\"",
    "\"<-\"",
    "\"?\"",
    "\"\\\"\"",
    "<REG_INT>",
    "<REG_DOUBLE>",
    "<REG_IDENTPRIME>",
    "<REG_IDENT>",
  };

}
